### ISSUE TITLE
Hi，this is 48000 sampling rate model？

### ISSUE THREAD

**Issue by ghost** [park-cheol/Speech_Enhancement-DCCRN#1]

**Comment by PoKoHA** [comment]
Yes, i downloaded Dataset from https://datashare.ed.ac.uk/handle/10283/2791

**Comment by ghost** [comment]
Thank you for your reply,  if I use DCCRN-E, how can I implement a real-time processing interface? Can you give me some suggestions？Thanks！

**Comment by PoKoHA** [comment]
Sorry, i have no idea.
