### ISSUE TITLE
The version of PyTorch

### ISSUE THREAD

**Issue by Blakey-Gavin** [park-cheol/Speech_Enhancement-DCCRN#2]
Hello, I am using your code, but I have some problems as follows:
![image](https://user-images.githubusercontent.com/104077097/172279699-724e1d39-a7fa-4fac-b5cf-d417de29a030.png)

At first, I used the version of '1.11.0+cu113' with the above error. Then I used '1.7.1+cu110' with the above error.

I want to ask that what's the version of pytorch in your code?

Thanks!

**Comment by PoKoHA** [comment]
I`m using
torch==1.7.0
torchaudio==0.7.0 (GPU: RTX2060Super)

Check out the compute capability of your GPU at https://developer.nvidia.com/cuda-gpus.

Then set it using 
$ export TORCH_CUDA_ARCH_LIST=<compute capability> 
and try reinstalling pytorch.

**Comment by Blakey-Gavin** [comment]
ok,I‘ll try it your way.Thank you for your answer!
